### ISSUE TITLE
求解答一下具体的模型导入步骤 纯小白 目前卡在导入模型这一关

### ISSUE THREAD

**Issue by DearCrazyLeaf** [samyycX/CS2-PlayerModelChanger#11]
我导入插件之后 可以正常运行 json文件也正常生成了，现在就是模型如何导入的问题，我看见您在下方回复的案例中有提到模型路径不要使用绝对路径而是相对路径，但是关于这一点我非常迷惑*（对于这方面一窍不通），

json文件如下：
<img width="671" alt="{E5ECF30B-475B-486d-99C0-B46B5D88E05C}" src="https://github.com/samyycX/CS2-PlayerModelChanger/assets/124550277/3f987077-0413-4287-909e-302f30ae41d1">

我要如何才能运用VPK文件中的相对路径并且正确的写出模型地址呢（而且这些模型包都是外置文件而非VPK文件，我必须要将其打包成VPK文件吗）

提前感谢大佬的解答 辛苦了

**Comment by DearCrazyLeaf** [comment]
如上图所示，我写出这些地址之后，在游戏中是没有显示这些模型选项的

**Comment by DearCrazyLeaf** [comment]
导入模型的问题已经解决了 现在是客户端只要一选用模型就会崩溃了

**Comment by samyycX** [comment]
把反斜杠换成普通斜杠

对于崩溃的问题，如果你在使用linux, 可以尝试使用noprecache版本，搭配1.0.4版本的ResourcePrecacher使用，把模型路径都写进去
如果你在使用windows，对崩溃的问题我也没有太好的解决方案，暂时不清楚崩溃是什么原因造成的，或许你可以试一下把模型从vpk提取出来，然后放在服务器目录内

**Comment by DearCrazyLeaf** [comment]
我闪退的时候服务器后台会先提示 Missing weapon hand bone attachment for player model.  猜测是模型手模的问题，请问这个插件只能导入一体的模型吗 手模可以导入吗

**Comment by samyycX** [comment]
> 我闪退的时候服务器后台会先提示 Missing weapon hand bone attachment for player model. 猜测是模型手模的问题，请问这个插件只能导入一体的模型吗 手模可以导入吗

是服务器崩溃还是客户端崩溃？
你用的这几个模型经过测试应该是不会导致崩溃的，或许可以先找其他模型测试一下？或者再确认一下是不是所有模型都会导致崩溃

**Comment by DearCrazyLeaf** [comment]
客户端闪退，有时候服务器也会突然闪退
是这样的 我在服务器上装了模型之后 后台看见是有加载模型的 

就像这样，（我是直接放在服务器本地加载的，因为如果直接使用characters/XXX/mymodel.vmdl路径的话客户端选择模型之后就会显示一个巨大的ERROR，所以我就把他放在服务器目录中了，客户端本地也在相同路径下放好了模型文件）然后这样加载完毕后客户端选择模型就会看不见自己的身体，如果拿起武器或者人物死亡就会导致客户端闪退（同时别人看我自己也是没有模型的，就像隐身了一样）

**Comment by DearCrazyLeaf** [comment]
![Uploading {100FB7FD-3D8B-41d0-A324-58E8BC17730B}.png…]()

**Comment by DearCrazyLeaf** [comment]
<img width="380" alt="{100FB7FD-3D8B-41d0-A324-58E8BC17730B}" src="https://github.com/samyycX/CS2-PlayerModelChanger/assets/124550277/f8e57b04-89b7-4487-a36b-9f25852e7ca9">

**Comment by DearCrazyLeaf** [comment]
然后关于模型的问题我使用的都是从创意工坊上下载的模型包有https://steamcommunity.com/sharedfiles/filedetails/?id=3186973222
https://steamcommunity.com/sharedfiles/filedetails/?id=3202038242
https://steamcommunity.com/sharedfiles/filedetails/?id=3186858913
并且里面的模型我测试了有大概10个左右 都是相同问题

**Comment by samyycX** [comment]
你有没有使用MultiAddonManager插件让客户端加载创意工坊资源？[关于MultiAddonManager](https://github.com/samyycX/CS2-PlayerModelChanger/blob/master/README_CN.md#%E8%AE%BE%E7%BD%AE-multiaddonmanager)

**Comment by samyycX** [comment]
> json文件如下： <img alt="{E5ECF30B-475B-486d-99C0-B46B5D88E05C}" width="671" src="https://private-user-images.githubusercontent.com/124550277/317846622-3f987077-0413-4287-909e-302f30ae41d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTIyNjcsIm5iZiI6MTcxMTcxMTk2NywicGF0aCI6Ii8xMjQ1NTAyNzcvMzE3ODQ2NjIyLTNmOTg3MDc3LTA0MTMtNDI4Ny05MDllLTMwMmYzMGFlNDFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMTMyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2FkYmU5Yzk1NmZiYWIyZDY0YTZmMjYwYWYzMDAwZGM1ZGIzNjlhN2M0Y2RkOWVkYmQ0ZTAzMzE3MDJkNDgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5dnqySAPXlFr7VvGbqaRN8iuE6tJYsOUZ3Wyp1De59c">

你这里的路径是正确的，把反斜杠改成正斜杠就可以了，不要使用C盘开始的绝对路径

**Comment by DearCrazyLeaf** [comment]
是的 我使用了MultiAddonManager插件添加了上述创意工坊ID的 然后加入服务器的时候确实提示下载这些创意工坊物品

我怀疑可能是我的相对路径正确了但是文件（模型）没有放对位置导致无法读取？ 请问服务器上下载好的创意工坊（模型）的文件是默认放在.\Counter-Strike Global Offensive\game\bin\win64\steamapps\workshop\content\730下吗？

**Comment by samyycX** [comment]
> 是的 我使用了MultiAddonManager插件添加了上述创意工坊ID的 然后加入服务器的时候确实提示下载这些创意工坊物品
> 
> 我怀疑可能是我的相对路径正确了但是文件（模型）没有放对位置导致无法读取？ 请问服务器上下载好的创意工坊（模型）的文件是默认放在.\Counter-Strike Global Offensive\game\bin\win64\steamapps\workshop\content\730下吗？

服务器理论上来说放不放模型都不会影响客户端模型的显示，只会影响一些动画（我自己的服务器就没有放模型文件）

**Comment by samyycX** [comment]
如果你的创意工坊物品加载成功的话，一般来说出现ERROR是路径问题

**Comment by DearCrazyLeaf** [comment]
好的 那我再去尝试解决一下路径问题吧 感谢大佬

**Comment by samyycX** [comment]
不介意的话可以把你目前配置的配置文件和对应的创意工坊id发在这里，我检查一下路径看看有没有问题

**Comment by samyycX** [comment]
也可以试一下服务器打开之后切换一次地图，再看看模型还是不是ERROR...这个问题曾经存在过，所以你可以试试

**Comment by DearCrazyLeaf** [comment]
<img width="1024" alt="dfca05fcead86fbc2d748b20e9824333" src="https://github.com/samyycX/CS2-PlayerModelChanger/assets/124550277/bc755a37-03a8-4be5-9b19-33ed3a39a850">
我按照安装步骤重新配置了一遍 现在已经可以正常加载模型了 非常感谢您的解答！推测问题大概率是因为创意工坊之前订阅过一次 导致文件提前下载了 不知什么原因客户端不会读取 我重新删除了之后再用服务器下载之后就可以正常显示了

**Comment by samyycX** [comment]
ok，问题已解决
