### ISSUE TITLE
ModelPlayer Error

### ISSUE THREAD

**Issue by Mr-Robot-ops** [samyycX/CS2-PlayerModelChanger#13]
Can you tell me where the error may lie

![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/6baa9101-2974-44d7-a258-bb8f29e4ad17)
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/cb02e3f5-c2cd-4131-8e0b-6c2e474da70a)
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/5f2aeaed-2737-4ff8-af6c-3c1c482b8036)
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/4999e0f4-2fca-4a75-ad0a-d015e9110b0e)
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/fb8d0dbe-175e-4f53-8c70-50276e13dff3)

**Comment by samyycX** [comment]
did you install and setup MultiAddonManager plugin properly to mount this workshop item?

**Comment by Mr-Robot-ops** [comment]
How is it mounted?
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/d68207a0-f097-4117-a4f3-f276889918e9)

**Comment by Mr-Robot-ops** [comment]
It's a pretty stupid mistake. But I discovered the mistake. I had the wrong files in "bin".
![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/b5d0c722-f1ec-4f23-92ad-10ef08c39ac0)

![grafik](https://github.com/samyycX/CS2-PlayerModelChanger/assets/55334802/8cb66d7a-41df-4610-a44e-e1a355ee4ea6)
