### ISSUE TITLE
No models ERROR

### ISSUE THREAD

**Issue by Narcotica** [samyycX/CS2-PlayerModelChanger#14]
We added models from the workshop.

// This configuration was automatically generated by CounterStrikeSharp for plugin 'PlayerModelChanger', at 2024/04/18 05:44:27
{
  "Models": {"Models": {
	// this configuration is an example, don't use it directly
	"model_index": {
		"name": "gura",// optional, default value is model index
		"path": "game/bin/linuxsteamrt64/steamapps/workshop/content/730/3202038242",
	},
	"mymodel": { // simplest
		"path": "game/bin/linuxsteamrt64/steamapps/workshop/content/730/3202038242",
	}
 },
  "MenuType": "chat",
  "StorageType": "sqlite",
  "MySQL_IP": "XX",
  "MySQL_Port": "3306",
  "MySQL_User": "XX",
  "MySQL_Password": "XX",
  "MySQL_Database": "s91829_playermodel",
  "MySQL_Table": "playermodelchanger",
  "DisablePrecache": false,
  "ConfigVersion": 1
}

This is our config file, you cant choose the mentioned model

**Comment by samyycX** [comment]
the path is the path to .vmdl model file in workshop vpk (for example `characters/.../xxx.vmdl`, not your workshop path.
Use source2viewer to open the workshop vpk and see the files in it

**Comment by sefinek** [comment]
> the path is the path to .vmdl model file in workshop vpk (for example `characters/.../xxx.vmdl`, not your workshop path. Use source2viewer to open the workshop vpk and see the files in it

That was useful, thanks
