### ISSUE TITLE
T-pose

### ISSUE THREAD

**Issue by zzy31** [samyycX/CS2-PlayerModelChanger#15]
Hello! I have installed your plugin and loaded the models, but I am experiencing an issue where they all load in the T-pose. However, from the first-person perspective, it looks fine. Is there a configuration for the movements to avoid the T-pose?
cfg
`"theflash_player_model": {
      "path": "characters/models/nozb1/theflash_player_model/theflash_player_model.vmdl",
      "side": "ALL"
    }`

**Comment by samyycX** [comment]
change the map once after you connect to the server, to make multiaddonmanager download the workshop vpk to server

**Comment by zzy31** [comment]
It worked, thank you!
