### ISSUE TITLE
Error sqlite

### ISSUE THREAD

**Issue by Dylan2004nn** [samyycX/CS2-PlayerModelChanger#16]
PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/PlayerModelChanger/PlayerModelChanger.dll
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'SQL logic error For more information on this error code see https://www.sqlite.org/rescode.html'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Storage.SqliteStorage.GetAllPlayerModel() in D:\development\PlayerModelChanger\storage\Sqlite.cs:line 26
   at Service.ModelService..ctor(ModelConfig Config, IStorage storage, IStringLocalizer localizer, DefaultModelManager defaultModelManager) in D:\development\PlayerModelChanger\Service.cs:line 36

**Comment by Dylan2004nn** [comment]
SQLite format 3   @                                                                     .fê
ø à àÉ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fƒ#tableplayersplayersCREATE TABLE `players` (
                    `steamid` UNSIGNED BIG INT NOT NULL,
                    `t_model` TEXT,
                    `ct_model` TEXT,
                    PRIMARY KEY (`steamid`))-A indexsqlite_autoindex_players_1players       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    

**Comment by samyycX** [comment]
try to remove this file and start the server again

**Comment by Dylan2004nn** [comment]
15:44:44 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/PlayerModelChanger/PlayerModelChanger.dll
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: players'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1184
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815
   at Storage.SqliteStorage.GetAllPlayerModel() in D:\development\PlayerModelChanger\storage\Sqlite.cs:line 26
   at Service.ModelService..ctor(ModelConfig Config, IStorage storage, IStringLocalizer localizer, DefaultModelManager defaultModelManager) in D:\development\PlayerModelChanger\Service.cs:line 36
   at PlayerModelChanger.PlayerModelChanger.Load(Boolean hotReload) in D:\development\PlayerModelChanger\PlayerModelChanger.cs:line 51
   
This is the error now

**Comment by Dylan2004nn** [comment]
Know its working idk what happen but its working, thanks!!

**Comment by Dylan2004nn** [comment]
Now is working idk how but is working, thanks!!
