### ISSUE TITLE
The offer that is needed

### ISSUE THREAD

**Issue by Gorbanev9999** [samyycX/CS2-PlayerModelChanger#17]
add the shutdown of the "random" command, because to the players who have been given the model via !modeladmin [all/steamid] set [all/ct/t] [model index] , the random key is available, and the skins are placed which they do not have access to

**Comment by samyycX** [comment]
!modeladmin is for admins, and @random key shouldn't give players models they don't have, can you show your config and which model have that issue?

**Comment by Gorbanev9999** [comment]
![Новый точечный рисунок (3)](https://github.com/samyycX/CS2-PlayerModelChanger/assets/72809266/e29a54e8-2032-4e43-a09f-4254dda308d7)

I give the player a skin through !modeladmin, 

![12](https://github.com/samyycX/CS2-PlayerModelChanger/assets/72809266/03bfd457-7111-4cd3-927c-7ea231d25586)

he goes into !md and presses random, and the skins go in a circle that are in the config

**Comment by samyycX** [comment]
"hideinmenu" can't restrict players to the model, you need to set like `"permissions": ["@custom/flag1"]`

**Comment by Gorbanev9999** [comment]
It is not convenient for each player to register flags manually

**Comment by samyycX** [comment]
> It is not convenient for each player to register flags manually

I don't exactly know what you want to do, if you want to force each player have a specific skin. you can use the DefaultModels feature. Or you can still use !modeladmin to set model for each player, but set a random flags that all player dont have instead of setting "hideinmenu" to true (set permission can both prevent player from using it by the random selection in menu and hide it in menu)

**Comment by samyycX** [comment]
> It is not convenient for each player to register flags manually, There are plugins that register automatically, but they reset models every 2-3 rounds

what permission plugins are you using

**Comment by samyycX** [comment]
inactive, reopen if you still have problem.
