### ISSUE TITLE
model just for a certain player

### ISSUE THREAD

**Issue by T3Marius** [samyycX/CS2-PlayerModelChanger#18]
It would've been cool to add a setting in plugin config that allows you to select what player you want to have a model. Something like this
Steam ID "64123719871239"
Model Name:
Mode PATH
Side: ALL

**Comment by samyycX** [comment]
maybe we can include this in "permissions" config, since it is more easy to implement it, like:
`"permissions": ["76561199xxxx"]`,
in this way it is possible to have more complex permission config, like: `"permissionsOr": ["76561199xxxx", "@custom/flag1"]`

**Comment by T3Marius** [comment]
> maybe we can include this in "permissions" config, since it is more easy to implement it, like: `"permissions": ["76561199xxxx"]`, in this way it is possible to have more complex permission config, like: `"permissionsOr": ["76561199xxxx", "@custom/flag1"]`

That would be great

**Comment by samyycX** [comment]
Supported in v1.4.0, check [Wiki](https://github.com/samyycX/CS2-PlayerModelChanger/wiki/Main-Configuration#modelforbots)
