### ISSUE TITLE
自定义模型无法在bot上使用

### ISSUE THREAD

**Issue by HuangQDZBC233** [samyycX/CS2-PlayerModelChanger#21]
![Desktop Screenshot 2024 06 08 - 10 32 42 94](https://github.com/samyycX/CS2-PlayerModelChanger/assets/78946199/78dabcd5-e073-4a5d-9627-b06f991dad2c)
![Counter-strike 2 Screenshot 2024 06 07 - 23 28 36 32](https://github.com/samyycX/CS2-PlayerModelChanger/assets/78946199/b1ae26f9-e1bc-4642-99d2-6af64de46f13)

**Comment by samyycX** [comment]
把 ModelsForBots 改成 ModelForBots

**Comment by HuangQDZBC233** [comment]
ok已解决
建议改下wiki
