### ISSUE TITLE
Model does not appear in the list

### ISSUE THREAD

**Issue by saikishogo** [samyycX/CS2-PlayerModelChanger#22]
![Counter-strike 2 Screenshot 2024 06 08 - 13 00 50 34](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/97da4dea-781b-4859-a7ca-c29fe3aad17e)
![スクリーンショット 2024-06-08 130121](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/584dc627-c662-4847-8516-03d5fb9c428d)
![スクリーンショット 2024-06-08 130136](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/250d1906-154f-4c64-b2cb-f69d20bfa54a)

When I add a model to PlayerModelChanger.json, it does not appear in the list, but when I create DefaultModels.json and select Default, the model I added appears for some reason and I get the error “Your model for All sides is Your model for All sides is invalid and it has been reset.
The configuration file is as shown in the image

**Comment by HuangQDZBC233** [comment]
set hideinmenu to false

**Comment by saikishogo** [comment]
> Hideinmenuをfalseに設定する

![Counter-strike 2 Screenshot 2024 06 08 - 13 55 54 73](https://github.com/samyycX/CS2-PlayerModelChanger/as
![スクリーンショット 2024-06-08 135723](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/963471bc-9d88-4d38-8201-0b246bcb3fa7)
![スクリーンショット 2024-06-08 135732](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/5b3806c3-af86-476b-aeff-25f41bd38fcb)
sets/91714554/72a470ce-8780-4f52-b924-479ca808bbbf)

I tried adding several models with unnecessary options removed, but it did not change.

**Comment by saikishogo** [comment]
> set hideinmenu to false

![Counter-strike 2 Screenshot 2024 06 08 - 13 55 54 73](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/cc932907-cc80-4ca4-9e80-d68b843842de)
![スクリーンショット 2024-06-08 135723](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/daa41176-62c8-4de8-8aec-d8c853a5accb)
![スクリーンショット 2024-06-08 135732](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/798a9925-b7c9-4550-968c-cf45111fc92e)

I tried adding several models with unnecessary options removed, but it did not change.

**Comment by saikishogo** [comment]
> set hideinmenu to false

![Counter-strike 2 Screenshot 2024 06 08 - 13 55 54 73](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/c1d65c78-3592-46e1-87d5-d07a9c63bac5)
![スクリーンショット 2024-06-08 140700](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/c2e5dc3b-aa2e-4243-b0ff-bca16b32e35b)
![スクリーンショット 2024-06-08 135732](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/f287e3a1-2ba9-44ae-b1cb-832f1c422e2e)

I tried adding several models with unnecessary options removed, but it did not change.

**Comment by samyycX** [comment]
set the “side” to `T` or `CT` or `ALL`

**Comment by saikishogo** [comment]
> set the “side” to `T` or `CT` or `ALL`

![Counter-strike 2 Screenshot 2024 06 08 - 14 27 35 04](https://github.com/samyycX/CS2-PlayerModelChanger/assets/91714554/fe8d455c-47fd-45ff-b368-fb28306a6b15)

The model name is now displayed and the model is loaded, but the 'Your model for All sides is invalid and it has been reset.' error is still displayed and does not appear when other model settings are added to PlayerModelChanger.json and DefaultModels.json, all the other model settings are no longer displayed.

**Comment by samyycX** [comment]
every DefaultModels config should have only one "index" configured, check wiki, 
and please put all your configs here (and hide sensitive information)

**Comment by saikishogo** [comment]
There was a missing column in PlayerModelChanger.json, which was corrected and now works correctly.
Thank you very much.
