### ISSUE TITLE
不支持WASD操控菜单，且版本号依然是1.4.1

### ISSUE THREAD

**Issue by Soramagic7** [samyycX/CS2-PlayerModelChanger#25]
我使用的是大佬最新的1.5.0支持WASDAPI操控菜单的版本
但是我控制台输入css_plugins list 显示为版本为1.4.1，并且也不能用WASD操控。

[Client]   List of all plugins currently loaded by CounterStrikeSharp: 6 plugins loaded.
[Client]   [#1:LOADED]: "[Custom] Map Configurator" (V. 1.0.2 [Beta]) by Manifest @Road To Glory
[Client]     Allow server owners to easily create unique configuration files on a per map basis.
[Client]   [#2:LOADED]: "Player Model Changer" (1.4.1) by samyyc
[Client]   [#3:LOADED]: "Resource Precacher" (1.0.6 (release)) by Nexd @ Eternar (https://eternar.dev)
[Client]     Automatically precache resources.
[Client]   [#4:LOADED]: "Practice Plugin" (1.0.0.3) by CHR15 & Grükan
[Client]   [#5:LOADED]: "InventorySimulator" (1.2.0) by Ian Lucas
[Client]     Inventory Simulator (inventory.cstrike.app)
[Client]   [#6:LOADED]: "WASDMenuAPI" (1.0.2) by Interesting

我试着重装了几遍这个插件，但是这个问题没有得到解决。

**Comment by samyycX** [comment]
我上传的Release版本忘记改版本号了，不好意思..
使用wasd菜单需要在 `PlayerModelChanger.json` 配置文件里将 `MenuType` 改为 `interactive`，如果还是不行的话请重新下载一遍Release

**Comment by Soramagic7** [comment]
问题已解决！
但是这个API没有返回上一级的按钮，是否可以在我们插件加一个返回上一级的选项？

**Comment by samyycX** [comment]
> 问题已解决！ 但是这个API没有返回上一级的按钮，是否可以在我们插件加一个返回上一级的选项？

我明天看看能不能做

**Comment by Soramagic7** [comment]
非常感谢大佬！
