### ISSUE TITLE
unloading bug

### ISSUE THREAD

**Issue by exkludera** [samyycX/CS2-PlayerModelChanger#28]
https://github.com/samyycX/CS2-PlayerModelChanger/blob/5fd61728dfe4741de1e0766d2023770e9f57d8f4/PlayerModelChanger.cs#L46

this isn't working properly for me😿
it triggers when i'm just starting the server, unloading EventPlayerSpawn & OnServerPrecacheResources

**Comment by samyycX** [comment]
can you confirm that the plugin works after delete this line?

**Comment by exkludera** [comment]
> can you confirm that the plugin works after delete this line?

yes everything works fine for me after I removed it.

**Comment by samyycX** [comment]
> > can you confirm that the plugin works after delete this line?
> 
> yes everything works fine for me after I removed it.

I think there is no problem to remove this line. i will push the fix after making some improvement
