### ISSUE TITLE
WASD

### ISSUE THREAD

**Issue by IRedbrine** [samyycX/CS2-PlayerModelChanger#30]
How enable/install de WASD Plugin?

**Comment by samyycX** [comment]
that plugin link is given in my readme

**Comment by IRedbrine** [comment]
i know, i put the plugin in my server but dnt work, have any tutor for active ?
-

**Comment by fpaezf** [comment]
> ## i know, i put the plugin in my server but dnt work, have any tutor for active ?

Same issue here!

**Comment by samyycX** [comment]
no longer depends on that plugin.
