### ISSUE TITLE
【功能性需求】不知道您是否有在此插件中添加给模型换皮的功能？

### ISSUE THREAD

**Issue by DearCrazyLeaf** [samyycX/CS2-PlayerModelChanger#34]
能否像其他大型社区一样提供一个换模型衣服的功能？在Source2Viewer中有些模型是有多个Mesh Group的，并且可以更换，但是我在目前的公开插件中都未找到相应的方法，请问大佬是否有做此功能或者有做此功能的意向？
![e071f53720be5a25628753bcc6d41729](https://github.com/user-attachments/assets/3ee8844a-4ac5-4805-81ca-de87db384ec9)

**Comment by samyycX** [comment]
会尝试一下，可否提供一个有多meshgroup的模型？

**Comment by DearCrazyLeaf** [comment]
> 会尝试一下，可否提供一个有多meshgroup的模型？

方便给一个联系方式吗？我们有很多支持更换组件的模型，但是是非公开的

**Comment by DearCrazyLeaf** [comment]
> 会尝试一下，可否提供一个有多meshgroup的模型？

我们的QQ群 342289459
