### ISSUE TITLE
请问权限组的定义如何操作

### ISSUE THREAD

**Issue by CeLicat** [samyycX/CS2-PlayerModelChanger#4]
"permissions": ["@vip/flag"]里提到的@vip/flag是如何或者是在哪里定义的，在教程里面找不到相关的描述

**Comment by samyycX** [comment]
这个是自定义的，在admins.json里面或者通过其他插件定义的flag
详细请看：https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

**Comment by CeLicat** [comment]
> 这个是自定义的，在admins.json里面或者通过其他插件定义的flag 详细请看：https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

非常感谢您的解答！
