### ISSUE TITLE
error

### ISSUE THREAD

**Issue by emiya011** [samyycX/CS2-PlayerModelChanger#6]
![b0a4cd2bd70427b7537775d3602802d](https://github.com/samyycX/CS2-PlayerModelChanger/assets/104676829/c229cba6-58db-40d3-a34f-3ae0c184b5dd)
Player Model Changer loaded 1 model(s) successfully.but the model in game is ERROR.Where should I put the model?
![d83f40751a6a8b37119e37a7a534ff3](https://github.com/samyycX/CS2-PlayerModelChanger/assets/104676829/4e4947b4-5c34-41f2-980e-db5d46861248)
Like this, how do I load the full model？

**Comment by samyycX** [comment]
See https://github.com/samyycX/CS2-PlayerModelChanger?tab=readme-ov-file#how-to-add-your-own-model

**Comment by samyycX** [comment]
See https://github.com/samyycX/CS2-PlayerModelChanger?tab=readme-ov-file#how-to-add-your-own-model
